include:
  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - lint
  - build
  - tests
  - secret-detection
  - publish-image
  - deploy-dev

variables:
  SECRET_DETECTION_ENABLED: 'true'

lint:
  stage: lint

build:
  stage: build

unit-test:
  stage: tests

secret_detection:
  stage: secret-detection

publish-image:
  stage: publish-image

deploy:
  stage: deploy-dev